spring:
  application:
    name: micro-service-order
  jackson:
    default-property-inclusion: non_null
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'Asia/Shanghai'
    serialization:
      indent_output: true
      fail_on_empty_beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yu19970501
    url: jdbc:mysql://localhost:3306/orders?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: org.yuwb.model
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 1
server:
  port: 9011
dubbo:
  scan:
    base-packages: org.yuwb.provider
  protocol:
    name: dubbo
    port: 12349
  registry:
    address: nacos://172.16.173.128:8848
